// Code generated by resolve_sparse_checkout.py; DO NOT EDIT.
package replay

_addons: {
	"account": {
		dir: "addons/account"
		depends: [
			"analytic",
			"base_setup",
			"digest",
			"onboarding",
			"portal",
			"product",
		]
		has_tests: true
	}
	"account_add_gln": {
		dir: "addons/account_add_gln"
		depends: [
			"account",
		]
		has_tests: false
	}
	"account_check_printing": {
		dir: "addons/account_check_printing"
		depends: [
			"account",
		]
		has_tests: true
	}
	"account_debit_note": {
		dir: "addons/account_debit_note"
		depends: [
			"account",
		]
		has_tests: true
	}
	"account_edi": {
		dir: "addons/account_edi"
		depends: [
			"account",
		]
		has_tests: true
	}
	"account_edi_proxy_client": {
		dir: "addons/account_edi_proxy_client"
		depends: [
			"account",
			"certificate",
		]
		has_tests: false
	}
	"account_edi_ubl_cii": {
		dir: "addons/account_edi_ubl_cii"
		depends: [
			"account",
		]
		has_tests: true
	}
	"account_fleet": {
		dir: "addons/account_fleet"
		depends: [
			"account",
			"fleet",
		]
		has_tests: true
	}
	"account_payment": {
		dir: "addons/account_payment"
		depends: [
			"account",
			"payment",
		]
		has_tests: true
	}
	"account_payment_interco": {
		dir: "addons/account_payment_interco"
		depends: [
			"account_payment",
		]
		has_tests: true
	}
	"account_peppol": {
		dir: "addons/account_peppol"
		depends: [
			"account_edi_proxy_client",
			"account_edi_ubl_cii",
		]
		has_tests: true
	}
	"account_peppol_advanced_fields": {
		dir: "addons/account_peppol_advanced_fields"
		depends: [
			"account",
			"account_edi_ubl_cii",
		]
		has_tests: false
	}
	"account_peppol_response": {
		dir: "addons/account_peppol_response"
		depends: [
			"account_peppol",
		]
		has_tests: true
	}
	"account_qr_code_emv": {
		dir: "addons/account_qr_code_emv"
		depends: [
			"account",
		]
		has_tests: false
	}
	"account_qr_code_sepa": {
		dir: "addons/account_qr_code_sepa"
		depends: [
			"account",
			"base_iban",
		]
		has_tests: true
	}
	"account_tax_python": {
		dir: "addons/account_tax_python"
		depends: [
			"account",
		]
		has_tests: true
	}
	"account_test": {
		dir: "addons/account_test"
		depends: [
			"account",
		]
		has_tests: false
	}
	"account_update_tax_tags": {
		dir: "addons/account_update_tax_tags"
		depends: [
			"account",
		]
		has_tests: true
	}
	"analytic": {
		dir: "addons/analytic"
		depends: [
			"base",
			"mail",
			"uom",
		]
		has_tests: true
	}
	"api_doc": {
		dir: "addons/api_doc"
		depends: [
			"web",
		]
		has_tests: true
	}
	"attachment_indexation": {
		dir: "addons/attachment_indexation"
		depends: [
			"web",
		]
		has_tests: true
	}
	"auth_ldap": {
		dir: "addons/auth_ldap"
		depends: [
			"base",
			"base_setup",
		]
		has_tests: true
	}
	"auth_oauth": {
		dir: "addons/auth_oauth"
		depends: [
			"auth_signup",
			"base",
			"base_setup",
			"web",
		]
		has_tests: false
	}
	"auth_passkey": {
		dir: "addons/auth_passkey"
		depends: [
			"base_setup",
			"web",
		]
		has_tests: true
	}
	"auth_passkey_portal": {
		dir: "addons/auth_passkey_portal"
		depends: [
			"auth_passkey",
			"portal",
		]
		has_tests: true
	}
	"auth_password_policy": {
		dir: "addons/auth_password_policy"
		depends: [
			"base_setup",
			"web",
		]
		has_tests: false
	}
	"auth_password_policy_portal": {
		dir: "addons/auth_password_policy_portal"
		depends: [
			"auth_password_policy",
			"portal",
		]
		has_tests: false
	}
	"auth_password_policy_signup": {
		dir: "addons/auth_password_policy_signup"
		depends: [
			"auth_password_policy",
			"auth_signup",
		]
		has_tests: false
	}
	"auth_signup": {
		dir: "addons/auth_signup"
		depends: [
			"base_setup",
			"mail",
			"web",
		]
		has_tests: true
	}
	"auth_timeout": {
		dir: "addons/auth_timeout"
		depends: [
			"auth_passkey",
			"auth_totp",
			"auth_totp_mail",
			"bus",
		]
		has_tests: true
	}
	"auth_totp": {
		dir: "addons/auth_totp"
		depends: [
			"web",
		]
		has_tests: true
	}
	"auth_totp_mail": {
		dir: "addons/auth_totp_mail"
		depends: [
			"auth_totp",
			"mail",
		]
		has_tests: true
	}
	"auth_totp_portal": {
		dir: "addons/auth_totp_portal"
		depends: [
			"auth_totp",
			"portal",
		]
		has_tests: true
	}
	"barcodes": {
		dir: "addons/barcodes"
		depends: [
			"web",
		]
		has_tests: true
	}
	"barcodes_gs1_nomenclature": {
		dir: "addons/barcodes_gs1_nomenclature"
		depends: [
			"barcodes",
			"uom",
		]
		has_tests: true
	}
	"base": {
		dir: "odoo/addons/base"
		depends: []
		has_tests: true
	}
	"base_address_extended": {
		dir: "addons/base_address_extended"
		depends: [
			"base",
			"contacts",
		]
		has_tests: true
	}
	"base_automation": {
		dir: "addons/base_automation"
		depends: [
			"base",
			"digest",
			"mail",
			"resource",
			"sms",
		]
		has_tests: true
	}
	"base_geolocalize": {
		dir: "addons/base_geolocalize"
		depends: [
			"base_setup",
		]
		has_tests: true
	}
	"base_iban": {
		dir: "addons/base_iban"
		depends: [
			"account",
			"web",
		]
		has_tests: false
	}
	"base_import": {
		dir: "addons/base_import"
		depends: [
			"web",
		]
		has_tests: false
	}
	"base_import_module": {
		dir: "addons/base_import_module"
		depends: [
			"web",
		]
		has_tests: true
	}
	"base_install_request": {
		dir: "addons/base_install_request"
		depends: [
			"mail",
		]
		has_tests: false
	}
	"base_setup": {
		dir: "addons/base_setup"
		depends: [
			"base",
			"web",
		]
		has_tests: true
	}
	"base_sparse_field": {
		dir: "addons/base_sparse_field"
		depends: [
			"base",
		]
		has_tests: true
	}
	"base_vat": {
		dir: "addons/base_vat"
		depends: [
			"account",
		]
		has_tests: true
	}
	"board": {
		dir: "addons/board"
		depends: [
			"spreadsheet_dashboard",
		]
		has_tests: false
	}
	"bus": {
		dir: "addons/bus"
		depends: [
			"base",
			"web",
		]
		has_tests: true
	}
	"calendar": {
		dir: "addons/calendar"
		depends: [
			"base",
			"mail",
		]
		has_tests: true
	}
	"calendar_sms": {
		dir: "addons/calendar_sms"
		depends: [
			"calendar",
			"sms",
		]
		has_tests: true
	}
	"certificate": {
		dir: "addons/certificate"
		depends: [
			"base_setup",
		]
		has_tests: true
	}
	"cloud_storage": {
		dir: "addons/cloud_storage"
		depends: [
			"base_setup",
			"mail",
		]
		has_tests: true
	}
	"cloud_storage_azure": {
		dir: "addons/cloud_storage_azure"
		depends: [
			"cloud_storage",
		]
		has_tests: true
	}
	"cloud_storage_google": {
		dir: "addons/cloud_storage_google"
		depends: [
			"cloud_storage",
		]
		has_tests: true
	}
	"cloud_storage_migration": {
		dir: "addons/cloud_storage_migration"
		depends: [
			"cloud_storage",
		]
		has_tests: true
	}
	"contacts": {
		dir: "addons/contacts"
		depends: [
			"base",
			"mail",
		]
		has_tests: true
	}
	"crm": {
		dir: "addons/crm"
		depends: [
			"base_setup",
			"calendar",
			"contacts",
			"digest",
			"mail",
			"phone_validation",
			"resource",
			"sales_team",
			"utm",
			"web_tour",
		]
		has_tests: true
	}
	"crm_iap_enrich": {
		dir: "addons/crm_iap_enrich"
		depends: [
			"iap_crm",
			"iap_mail",
		]
		has_tests: true
	}
	"crm_iap_mine": {
		dir: "addons/crm_iap_mine"
		depends: [
			"iap_crm",
			"iap_mail",
		]
		has_tests: true
	}
	"crm_livechat": {
		dir: "addons/crm_livechat"
		depends: [
			"crm",
			"im_livechat",
		]
		has_tests: true
	}
	"crm_mail_plugin": {
		dir: "addons/crm_mail_plugin"
		depends: [
			"crm",
			"mail_plugin",
		]
		has_tests: true
	}
	"crm_sms": {
		dir: "addons/crm_sms"
		depends: [
			"crm",
			"sms",
		]
		has_tests: true
	}
	"data_recycle": {
		dir: "addons/data_recycle"
		depends: [
			"mail",
		]
		has_tests: true
	}
	"delivery": {
		dir: "addons/delivery"
		depends: [
			"payment_custom",
			"sale",
		]
		has_tests: true
	}
	"delivery_mondialrelay": {
		dir: "addons/delivery_mondialrelay"
		depends: [
			"stock_delivery",
		]
		has_tests: false
	}
	"delivery_stock_picking_batch": {
		dir: "addons/delivery_stock_picking_batch"
		depends: [
			"stock_delivery",
			"stock_picking_batch",
		]
		has_tests: true
	}
	"digest": {
		dir: "addons/digest"
		depends: [
			"mail",
			"portal",
			"resource",
		]
		has_tests: true
	}
	"event": {
		dir: "addons/event"
		depends: [
			"barcodes",
			"base_setup",
			"mail",
			"phone_validation",
			"portal",
			"utm",
		]
		has_tests: true
	}
	"event_booth": {
		dir: "addons/event_booth"
		depends: [
			"event",
		]
		has_tests: true
	}
	"event_booth_sale": {
		dir: "addons/event_booth_sale"
		depends: [
			"event_booth",
			"event_sale",
		]
		has_tests: true
	}
	"event_crm": {
		dir: "addons/event_crm"
		depends: [
			"crm",
			"event",
		]
		has_tests: true
	}
	"event_crm_sale": {
		dir: "addons/event_crm_sale"
		depends: [
			"event_crm",
			"event_sale",
		]
		has_tests: true
	}
	"event_product": {
		dir: "addons/event_product"
		depends: [
			"account",
			"event",
			"product",
		]
		has_tests: true
	}
	"event_sale": {
		dir: "addons/event_sale"
		depends: [
			"event_product",
			"sale_management",
		]
		has_tests: true
	}
	"event_sms": {
		dir: "addons/event_sms"
		depends: [
			"event",
			"sms",
		]
		has_tests: true
	}
	"fleet": {
		dir: "addons/fleet"
		depends: [
			"base",
			"mail",
		]
		has_tests: true
	}
	"gamification": {
		dir: "addons/gamification"
		depends: [
			"mail",
		]
		has_tests: true
	}
	"gamification_sale_crm": {
		dir: "addons/gamification_sale_crm"
		depends: [
			"gamification",
			"sale_crm",
		]
		has_tests: false
	}
	"google_account": {
		dir: "addons/google_account"
		depends: [
			"base_setup",
		]
		has_tests: false
	}
	"google_address_autocomplete": {
		dir: "addons/google_address_autocomplete"
		depends: [
			"web",
		]
		has_tests: true
	}
	"google_calendar": {
		dir: "addons/google_calendar"
		depends: [
			"calendar",
			"google_account",
		]
		has_tests: true
	}
	"google_gmail": {
		dir: "addons/google_gmail"
		depends: [
			"mail",
		]
		has_tests: true
	}
	"google_recaptcha": {
		dir: "addons/google_recaptcha"
		depends: [
			"base_setup",
		]
		has_tests: false
	}
	"hr": {
		dir: "addons/hr"
		depends: [
			"base_setup",
			"digest",
			"phone_validation",
			"resource_mail",
			"web",
		]
		has_tests: true
	}
	"hr_attendance": {
		dir: "addons/hr_attendance"
		depends: [
			"barcodes",
			"base_geolocalize",
			"hr",
		]
		has_tests: true
	}
	"hr_calendar": {
		dir: "addons/hr_calendar"
		depends: [
			"calendar",
			"hr",
		]
		has_tests: true
	}
	"hr_expense": {
		dir: "addons/hr_expense"
		depends: [
			"account",
			"hr",
			"web_tour",
		]
		has_tests: true
	}
	"hr_fleet": {
		dir: "addons/hr_fleet"
		depends: [
			"fleet",
			"hr",
		]
		has_tests: true
	}
	"hr_gamification": {
		dir: "addons/hr_gamification"
		depends: [
			"gamification",
			"hr",
		]
		has_tests: true
	}
	"hr_holidays": {
		dir: "addons/hr_holidays"
		depends: [
			"calendar",
			"hr",
			"resource",
		]
		has_tests: true
	}
	"hr_holidays_attendance": {
		dir: "addons/hr_holidays_attendance"
		depends: [
			"hr_attendance",
			"hr_holidays",
		]
		has_tests: true
	}
	"hr_holidays_homeworking": {
		dir: "addons/hr_holidays_homeworking"
		depends: [
			"hr_holidays",
			"hr_homeworking",
		]
		has_tests: false
	}
	"hr_homeworking": {
		dir: "addons/hr_homeworking"
		depends: [
			"hr",
		]
		has_tests: true
	}
	"hr_homeworking_calendar": {
		dir: "addons/hr_homeworking_calendar"
		depends: [
			"calendar",
			"hr_homeworking",
		]
		has_tests: true
	}
	"hr_hourly_cost": {
		dir: "addons/hr_hourly_cost"
		depends: [
			"hr",
		]
		has_tests: false
	}
	"hr_livechat": {
		dir: "addons/hr_livechat"
		depends: [
			"hr",
			"im_livechat",
		]
		has_tests: false
	}
	"hr_maintenance": {
		dir: "addons/hr_maintenance"
		depends: [
			"hr",
			"maintenance",
		]
		has_tests: false
	}
	"hr_org_chart": {
		dir: "addons/hr_org_chart"
		depends: [
			"hr",
			"web_hierarchy",
		]
		has_tests: true
	}
	"hr_presence": {
		dir: "addons/hr_presence"
		depends: [
			"hr",
			"hr_holidays",
			"sms",
		]
		has_tests: false
	}
	"hr_recruitment": {
		dir: "addons/hr_recruitment"
		depends: [
			"attachment_indexation",
			"calendar",
			"digest",
			"hr",
			"utm",
			"web_tour",
		]
		has_tests: true
	}
	"hr_recruitment_skills": {
		dir: "addons/hr_recruitment_skills"
		depends: [
			"hr_recruitment",
			"hr_skills",
		]
		has_tests: true
	}
	"hr_recruitment_sms": {
		dir: "addons/hr_recruitment_sms"
		depends: [
			"hr_recruitment",
			"sms",
		]
		has_tests: false
	}
	"hr_recruitment_survey": {
		dir: "addons/hr_recruitment_survey"
		depends: [
			"hr_recruitment",
			"survey",
		]
		has_tests: true
	}
	"hr_skills": {
		dir: "addons/hr_skills"
		depends: [
			"hr",
		]
		has_tests: true
	}
	"hr_skills_event": {
		dir: "addons/hr_skills_event"
		depends: [
			"event",
			"hr_skills",
		]
		has_tests: true
	}
	"hr_skills_slides": {
		dir: "addons/hr_skills_slides"
		depends: [
			"hr_skills",
			"website_slides",
		]
		has_tests: true
	}
	"hr_skills_survey": {
		dir: "addons/hr_skills_survey"
		depends: [
			"hr_skills",
			"survey",
		]
		has_tests: true
	}
	"hr_timesheet": {
		dir: "addons/hr_timesheet"
		depends: [
			"analytic",
			"hr",
			"hr_hourly_cost",
			"project",
			"uom",
		]
		has_tests: true
	}
	"hr_timesheet_attendance": {
		dir: "addons/hr_timesheet_attendance"
		depends: [
			"hr_attendance",
			"hr_timesheet",
		]
		has_tests: true
	}
	"hr_work_entry": {
		dir: "addons/hr_work_entry"
		depends: [
			"hr",
		]
		has_tests: true
	}
	"hr_work_entry_holidays": {
		dir: "addons/hr_work_entry_holidays"
		depends: [
			"hr_holidays",
			"hr_work_entry",
		]
		has_tests: true
	}
	"html_builder": {
		dir: "addons/html_builder"
		depends: [
			"base",
			"html_editor",
			"mail",
		]
		has_tests: true
	}
	"html_editor": {
		dir: "addons/html_editor"
		depends: [
			"base",
			"bus",
			"web",
		]
		has_tests: true
	}
	"http_routing": {
		dir: "addons/http_routing"
		depends: [
			"web",
		]
		has_tests: true
	}
	"iap": {
		dir: "addons/iap"
		depends: [
			"base_setup",
			"web",
		]
		has_tests: true
	}
	"iap_crm": {
		dir: "addons/iap_crm"
		depends: [
			"crm",
			"iap_mail",
		]
		has_tests: false
	}
	"iap_mail": {
		dir: "addons/iap_mail"
		depends: [
			"iap",
			"mail",
		]
		has_tests: false
	}
	"im_livechat": {
		dir: "addons/im_livechat"
		depends: [
			"digest",
			"mail",
			"rating",
			"utm",
		]
		has_tests: true
	}
	"iot_base": {
		dir: "addons/iot_base"
		depends: [
			"web",
		]
		has_tests: false
	}
	"iot_box_image": {
		dir: "addons/iot_box_image"
		depends: []
		has_tests: false
	}
	"iot_drivers": {
		dir: "addons/iot_drivers"
		depends: []
		has_tests: false
	}
	"l10n_account_edi_ubl_cii_tests": {
		dir: "addons/l10n_account_edi_ubl_cii_tests"
		depends: [
			"account_edi_ubl_cii",
			"l10n_au",
			"l10n_be",
			"l10n_de",
			"l10n_fr_account",
			"l10n_nl",
		]
		has_tests: true
	}
	"l10n_account_withholding_tax": {
		dir: "addons/l10n_account_withholding_tax"
		depends: [
			"account",
		]
		has_tests: true
	}
	"l10n_account_withholding_tax_pos": {
		dir: "addons/l10n_account_withholding_tax_pos"
		depends: [
			"l10n_account_withholding_tax",
			"point_of_sale",
		]
		has_tests: false
	}
	"l10n_ae": {
		dir: "addons/l10n_ae"
		depends: [
			"account",
			"l10n_gcc_invoice",
		]
		has_tests: false
	}
	"l10n_ae_pos": {
		dir: "addons/l10n_ae_pos"
		depends: [
			"l10n_ae",
			"l10n_gcc_pos",
		]
		has_tests: false
	}
	"l10n_anz_ubl_pint": {
		dir: "addons/l10n_anz_ubl_pint"
		depends: [
			"account_edi_ubl_cii",
		]
		has_tests: true
	}
	"l10n_ar": {
		dir: "addons/l10n_ar"
		depends: [
			"account",
			"l10n_latam_base",
			"l10n_latam_invoice_document",
		]
		has_tests: true
	}
	"l10n_ar_pos": {
		dir: "addons/l10n_ar_pos"
		depends: [
			"l10n_ar",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_ar_stock": {
		dir: "addons/l10n_ar_stock"
		depends: [
			"l10n_ar",
			"stock_account",
		]
		has_tests: true
	}
	"l10n_ar_website_sale": {
		dir: "addons/l10n_ar_website_sale"
		depends: [
			"l10n_ar",
			"website_sale",
		]
		has_tests: true
	}
	"l10n_ar_withholding": {
		dir: "addons/l10n_ar_withholding"
		depends: [
			"l10n_ar",
			"l10n_latam_check",
		]
		has_tests: true
	}
	"l10n_at": {
		dir: "addons/l10n_at"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
			"l10n_din5008",
		]
		has_tests: false
	}
	"l10n_au": {
		dir: "addons/l10n_au"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_bd": {
		dir: "addons/l10n_bd"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_be": {
		dir: "addons/l10n_be"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_be_pos_restaurant": {
		dir: "addons/l10n_be_pos_restaurant"
		depends: [
			"l10n_be",
			"pos_restaurant",
		]
		has_tests: false
	}
	"l10n_be_pos_sale": {
		dir: "addons/l10n_be_pos_sale"
		depends: [
			"l10n_be",
			"pos_sale",
		]
		has_tests: true
	}
	"l10n_bf": {
		dir: "addons/l10n_bf"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_bg": {
		dir: "addons/l10n_bg"
		depends: [
			"account",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_bg_ledger": {
		dir: "addons/l10n_bg_ledger"
		depends: [
			"l10n_bg",
		]
		has_tests: false
	}
	"l10n_bh": {
		dir: "addons/l10n_bh"
		depends: [
			"account",
			"l10n_gcc_invoice",
		]
		has_tests: false
	}
	"l10n_bj": {
		dir: "addons/l10n_bj"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_bo": {
		dir: "addons/l10n_bo"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_br": {
		dir: "addons/l10n_br"
		depends: [
			"account",
			"account_qr_code_emv",
			"base_address_extended",
			"l10n_latam_base",
			"l10n_latam_invoice_document",
		]
		has_tests: true
	}
	"l10n_br_sales": {
		dir: "addons/l10n_br_sales"
		depends: [
			"l10n_br",
			"sale",
		]
		has_tests: false
	}
	"l10n_br_website_sale": {
		dir: "addons/l10n_br_website_sale"
		depends: [
			"l10n_br",
			"website_sale",
		]
		has_tests: false
	}
	"l10n_ca": {
		dir: "addons/l10n_ca"
		depends: [
			"account",
			"base_iban",
		]
		has_tests: false
	}
	"l10n_cd": {
		dir: "addons/l10n_cd"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_cf": {
		dir: "addons/l10n_cf"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_cg": {
		dir: "addons/l10n_cg"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_ch": {
		dir: "addons/l10n_ch"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"l10n_din5008",
		]
		has_tests: true
	}
	"l10n_ch_pos": {
		dir: "addons/l10n_ch_pos"
		depends: [
			"l10n_ch",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_ci": {
		dir: "addons/l10n_ci"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_cl": {
		dir: "addons/l10n_cl"
		depends: [
			"account",
			"base_vat",
			"contacts",
			"l10n_latam_base",
			"l10n_latam_invoice_document",
			"uom",
		]
		has_tests: true
	}
	"l10n_cm": {
		dir: "addons/l10n_cm"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_cn": {
		dir: "addons/l10n_cn"
		depends: [
			"account",
			"base",
		]
		has_tests: false
	}
	"l10n_cn_city": {
		dir: "addons/l10n_cn_city"
		depends: [
			"base_address_extended",
			"l10n_cn",
		]
		has_tests: false
	}
	"l10n_co": {
		dir: "addons/l10n_co"
		depends: [
			"account",
			"account_debit_note",
			"l10n_latam_base",
		]
		has_tests: false
	}
	"l10n_co_pos": {
		dir: "addons/l10n_co_pos"
		depends: [
			"l10n_co",
			"point_of_sale",
		]
		has_tests: false
	}
	"l10n_cr": {
		dir: "addons/l10n_cr"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_cy": {
		dir: "addons/l10n_cy"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_cz": {
		dir: "addons/l10n_cz"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: true
	}
	"l10n_de": {
		dir: "addons/l10n_de"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
			"l10n_din5008",
		]
		has_tests: true
	}
	"l10n_din5008": {
		dir: "addons/l10n_din5008"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_din5008_expense": {
		dir: "addons/l10n_din5008_expense"
		depends: [
			"hr_expense",
			"l10n_din5008",
		]
		has_tests: false
	}
	"l10n_din5008_purchase": {
		dir: "addons/l10n_din5008_purchase"
		depends: [
			"l10n_din5008",
			"purchase",
		]
		has_tests: false
	}
	"l10n_din5008_repair": {
		dir: "addons/l10n_din5008_repair"
		depends: [
			"l10n_din5008",
			"repair",
		]
		has_tests: false
	}
	"l10n_din5008_sale": {
		dir: "addons/l10n_din5008_sale"
		depends: [
			"l10n_din5008",
			"sale",
		]
		has_tests: false
	}
	"l10n_din5008_stock": {
		dir: "addons/l10n_din5008_stock"
		depends: [
			"l10n_din5008",
			"stock",
		]
		has_tests: false
	}
	"l10n_dk": {
		dir: "addons/l10n_dk"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_dk_fik": {
		dir: "addons/l10n_dk_fik"
		depends: [
			"l10n_dk",
		]
		has_tests: false
	}
	"l10n_dk_nemhandel": {
		dir: "addons/l10n_dk_nemhandel"
		depends: [
			"account_edi_proxy_client",
			"account_edi_ubl_cii",
			"l10n_dk",
		]
		has_tests: true
	}
	"l10n_dk_nemhandel_response": {
		dir: "addons/l10n_dk_nemhandel_response"
		depends: [
			"l10n_dk_nemhandel",
		]
		has_tests: false
	}
	"l10n_dk_oioubl": {
		dir: "addons/l10n_dk_oioubl"
		depends: [
			"account_edi_ubl_cii",
			"l10n_dk",
		]
		has_tests: true
	}
	"l10n_do": {
		dir: "addons/l10n_do"
		depends: [
			"account",
			"base_iban",
		]
		has_tests: false
	}
	"l10n_dz": {
		dir: "addons/l10n_dz"
		depends: [
			"account",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_ec": {
		dir: "addons/l10n_ec"
		depends: [
			"account",
			"account_debit_note",
			"base",
			"base_iban",
			"l10n_latam_base",
			"l10n_latam_invoice_document",
		]
		has_tests: true
	}
	"l10n_ec_sale": {
		dir: "addons/l10n_ec_sale"
		depends: [
			"l10n_ec",
			"sale",
		]
		has_tests: true
	}
	"l10n_ec_stock": {
		dir: "addons/l10n_ec_stock"
		depends: [
			"l10n_ec",
			"stock",
		]
		has_tests: false
	}
	"l10n_ee": {
		dir: "addons/l10n_ee"
		depends: [
			"account",
			"account_edi_ubl_cii",
		]
		has_tests: false
	}
	"l10n_eg": {
		dir: "addons/l10n_eg"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_eg_edi_eta": {
		dir: "addons/l10n_eg_edi_eta"
		depends: [
			"account_edi",
			"l10n_eg",
		]
		has_tests: true
	}
	"l10n_es": {
		dir: "addons/l10n_es"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_es_edi_facturae": {
		dir: "addons/l10n_es_edi_facturae"
		depends: [
			"certificate",
			"l10n_es",
		]
		has_tests: true
	}
	"l10n_es_edi_sii": {
		dir: "addons/l10n_es_edi_sii"
		depends: [
			"account_edi",
			"certificate",
			"l10n_es",
		]
		has_tests: true
	}
	"l10n_es_edi_tbai": {
		dir: "addons/l10n_es_edi_tbai"
		depends: [
			"certificate",
			"l10n_es",
		]
		has_tests: true
	}
	"l10n_es_edi_tbai_pos": {
		dir: "addons/l10n_es_edi_tbai_pos"
		depends: [
			"l10n_es_edi_tbai",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_es_edi_verifactu": {
		dir: "addons/l10n_es_edi_verifactu"
		depends: [
			"certificate",
			"l10n_es",
		]
		has_tests: true
	}
	"l10n_es_edi_verifactu_pos": {
		dir: "addons/l10n_es_edi_verifactu_pos"
		depends: [
			"l10n_es_edi_verifactu",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_es_pos": {
		dir: "addons/l10n_es_pos"
		depends: [
			"l10n_es",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_et": {
		dir: "addons/l10n_et"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_eu_oss": {
		dir: "addons/l10n_eu_oss"
		depends: [
			"account",
		]
		has_tests: true
	}
	"l10n_fi": {
		dir: "addons/l10n_fi"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: true
	}
	"l10n_fi_sale": {
		dir: "addons/l10n_fi_sale"
		depends: [
			"l10n_fi",
			"sale",
		]
		has_tests: false
	}
	"l10n_fr": {
		dir: "addons/l10n_fr"
		depends: [
			"base",
		]
		has_tests: false
	}
	"l10n_fr_account": {
		dir: "addons/l10n_fr_account"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
			"l10n_fr",
		]
		has_tests: true
	}
	"l10n_fr_facturx_chorus_pro": {
		dir: "addons/l10n_fr_facturx_chorus_pro"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"l10n_fr_account",
		]
		has_tests: true
	}
	"l10n_fr_hr_holidays": {
		dir: "addons/l10n_fr_hr_holidays"
		depends: [
			"hr_holidays",
		]
		has_tests: true
	}
	"l10n_fr_hr_work_entry_holidays": {
		dir: "addons/l10n_fr_hr_work_entry_holidays"
		depends: [
			"hr_work_entry_holidays",
			"l10n_fr_hr_holidays",
		]
		has_tests: true
	}
	"l10n_fr_pdp": {
		dir: "addons/l10n_fr_pdp"
		depends: [
			"account_peppol_response",
			"auth_totp_mail",
			"iap",
			"l10n_fr_account",
		]
		has_tests: true
	}
	"l10n_fr_pdp_pos": {
		dir: "addons/l10n_fr_pdp_pos"
		depends: [
			"l10n_fr_pdp",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_fr_pos_cert": {
		dir: "addons/l10n_fr_pos_cert"
		depends: [
			"l10n_fr_account",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_ga": {
		dir: "addons/l10n_ga"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_gcc_invoice": {
		dir: "addons/l10n_gcc_invoice"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_gcc_invoice_stock_account": {
		dir: "addons/l10n_gcc_invoice_stock_account"
		depends: [
			"l10n_gcc_invoice",
			"stock_account",
		]
		has_tests: false
	}
	"l10n_gcc_pos": {
		dir: "addons/l10n_gcc_pos"
		depends: [
			"l10n_gcc_invoice",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_ge": {
		dir: "addons/l10n_ge"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_gf": {
		dir: "addons/l10n_gf"
		depends: [
			"account",
			"l10n_fr_account",
		]
		has_tests: false
	}
	"l10n_gn": {
		dir: "addons/l10n_gn"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_gp": {
		dir: "addons/l10n_gp"
		depends: [
			"account",
			"l10n_fr_account",
		]
		has_tests: false
	}
	"l10n_gq": {
		dir: "addons/l10n_gq"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_gr": {
		dir: "addons/l10n_gr"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_gr_edi": {
		dir: "addons/l10n_gr_edi"
		depends: [
			"l10n_gr",
		]
		has_tests: true
	}
	"l10n_gr_edi_e_invoo": {
		dir: "addons/l10n_gr_edi_e_invoo"
		depends: [
			"account_edi_proxy_client",
			"l10n_gr_edi",
		]
		has_tests: true
	}
	"l10n_gt": {
		dir: "addons/l10n_gt"
		depends: [
			"account",
			"base",
		]
		has_tests: false
	}
	"l10n_gw": {
		dir: "addons/l10n_gw"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_hk": {
		dir: "addons/l10n_hk"
		depends: [
			"account",
			"account_qr_code_emv",
		]
		has_tests: true
	}
	"l10n_hn": {
		dir: "addons/l10n_hn"
		depends: [
			"account",
			"base",
		]
		has_tests: false
	}
	"l10n_hr": {
		dir: "addons/l10n_hr"
		depends: [
			"account",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_hr_edi": {
		dir: "addons/l10n_hr_edi"
		depends: [
			"account_edi_ubl_cii",
			"account_peppol",
			"l10n_hr",
		]
		has_tests: true
	}
	"l10n_hr_kuna": {
		dir: "addons/l10n_hr_kuna"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_hu": {
		dir: "addons/l10n_hu"
		depends: [
			"account",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_hu_edi": {
		dir: "addons/l10n_hu_edi"
		depends: [
			"account_debit_note",
			"base_iban",
			"l10n_hu",
		]
		has_tests: true
	}
	"l10n_hu_edi_receive": {
		dir: "addons/l10n_hu_edi_receive"
		depends: [
			"l10n_hu_edi",
		]
		has_tests: true
	}
	"l10n_id": {
		dir: "addons/l10n_id"
		depends: [
			"account",
			"base_iban",
			"base_vat",
		]
		has_tests: true
	}
	"l10n_id_efaktur_coretax": {
		dir: "addons/l10n_id_efaktur_coretax"
		depends: [
			"l10n_id",
		]
		has_tests: true
	}
	"l10n_id_pos": {
		dir: "addons/l10n_id_pos"
		depends: [
			"l10n_id",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_ie": {
		dir: "addons/l10n_ie"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_il": {
		dir: "addons/l10n_il"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_in": {
		dir: "addons/l10n_in"
		depends: [
			"account",
			"account_debit_note",
			"account_tax_python",
			"base_vat",
			"iap",
		]
		has_tests: true
	}
	"l10n_in_edi": {
		dir: "addons/l10n_in_edi"
		depends: [
			"account_edi",
			"l10n_in",
		]
		has_tests: true
	}
	"l10n_in_ewaybill": {
		dir: "addons/l10n_in_ewaybill"
		depends: [
			"l10n_in",
		]
		has_tests: true
	}
	"l10n_in_ewaybill_irn": {
		dir: "addons/l10n_in_ewaybill_irn"
		depends: [
			"l10n_in_edi",
			"l10n_in_ewaybill",
		]
		has_tests: true
	}
	"l10n_in_ewaybill_stock": {
		dir: "addons/l10n_in_ewaybill_stock"
		depends: [
			"l10n_in_ewaybill",
			"l10n_in_stock",
		]
		has_tests: true
	}
	"l10n_in_hr_holidays": {
		dir: "addons/l10n_in_hr_holidays"
		depends: [
			"hr_holidays",
		]
		has_tests: true
	}
	"l10n_in_pos": {
		dir: "addons/l10n_in_pos"
		depends: [
			"l10n_in",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_in_purchase_stock": {
		dir: "addons/l10n_in_purchase_stock"
		depends: [
			"l10n_in_stock",
			"purchase_stock",
		]
		has_tests: false
	}
	"l10n_in_sale": {
		dir: "addons/l10n_in_sale"
		depends: [
			"l10n_in",
			"sale",
		]
		has_tests: true
	}
	"l10n_in_sale_stock": {
		dir: "addons/l10n_in_sale_stock"
		depends: [
			"l10n_in_sale",
			"l10n_in_stock",
			"sale_stock",
		]
		has_tests: false
	}
	"l10n_in_stock": {
		dir: "addons/l10n_in_stock"
		depends: [
			"l10n_in",
			"stock",
			"stock_account",
		]
		has_tests: false
	}
	"l10n_iq": {
		dir: "addons/l10n_iq"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_it": {
		dir: "addons/l10n_it"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_it_edi": {
		dir: "addons/l10n_it_edi"
		depends: [
			"account_debit_note",
			"account_edi_proxy_client",
			"l10n_it",
		]
		has_tests: true
	}
	"l10n_it_edi_doi": {
		dir: "addons/l10n_it_edi_doi"
		depends: [
			"l10n_it_edi",
			"sale",
		]
		has_tests: true
	}
	"l10n_it_edi_sale": {
		dir: "addons/l10n_it_edi_sale"
		depends: [
			"l10n_it_edi",
			"sale",
		]
		has_tests: true
	}
	"l10n_it_stock_ddt": {
		dir: "addons/l10n_it_stock_ddt"
		depends: [
			"l10n_it_edi",
			"stock_account",
			"stock_delivery",
		]
		has_tests: true
	}
	"l10n_jo": {
		dir: "addons/l10n_jo"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_jo_edi": {
		dir: "addons/l10n_jo_edi"
		depends: [
			"account_edi_ubl_cii",
			"l10n_jo",
		]
		has_tests: true
	}
	"l10n_jo_edi_pos": {
		dir: "addons/l10n_jo_edi_pos"
		depends: [
			"l10n_jo_edi",
			"pos_edi_ubl",
		]
		has_tests: true
	}
	"l10n_jp": {
		dir: "addons/l10n_jp"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_jp_ubl_pint": {
		dir: "addons/l10n_jp_ubl_pint"
		depends: [
			"account_edi_ubl_cii",
		]
		has_tests: true
	}
	"l10n_ke": {
		dir: "addons/l10n_ke"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_ke_edi_tremol": {
		dir: "addons/l10n_ke_edi_tremol"
		depends: [
			"l10n_ke",
		]
		has_tests: true
	}
	"l10n_kh": {
		dir: "addons/l10n_kh"
		depends: [
			"account_qr_code_emv",
			"l10n_account_withholding_tax",
		]
		has_tests: false
	}
	"l10n_km": {
		dir: "addons/l10n_km"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_kr": {
		dir: "addons/l10n_kr"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_kw": {
		dir: "addons/l10n_kw"
		depends: [
			"account",
			"l10n_gcc_invoice",
		]
		has_tests: false
	}
	"l10n_kz": {
		dir: "addons/l10n_kz"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_latam_base": {
		dir: "addons/l10n_latam_base"
		depends: [
			"base_vat",
			"contacts",
		]
		has_tests: false
	}
	"l10n_latam_check": {
		dir: "addons/l10n_latam_check"
		depends: [
			"account",
			"base_vat",
		]
		has_tests: true
	}
	"l10n_latam_invoice_document": {
		dir: "addons/l10n_latam_invoice_document"
		depends: [
			"account",
			"account_debit_note",
		]
		has_tests: false
	}
	"l10n_lb_account": {
		dir: "addons/l10n_lb_account"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_lk": {
		dir: "addons/l10n_lk"
		depends: [
			"account",
			"l10n_account_withholding_tax",
		]
		has_tests: false
	}
	"l10n_lk_invoice": {
		dir: "addons/l10n_lk_invoice"
		depends: [
			"l10n_lk",
		]
		has_tests: true
	}
	"l10n_lt": {
		dir: "addons/l10n_lt"
		depends: [
			"account",
			"account_edi_ubl_cii",
		]
		has_tests: false
	}
	"l10n_lu": {
		dir: "addons/l10n_lu"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_lv": {
		dir: "addons/l10n_lv"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_ma": {
		dir: "addons/l10n_ma"
		depends: [
			"account",
			"base",
		]
		has_tests: false
	}
	"l10n_mc": {
		dir: "addons/l10n_mc"
		depends: [
			"account",
			"l10n_fr_account",
		]
		has_tests: false
	}
	"l10n_ml": {
		dir: "addons/l10n_ml"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_mn": {
		dir: "addons/l10n_mn"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_mq": {
		dir: "addons/l10n_mq"
		depends: [
			"account",
			"l10n_fr_account",
		]
		has_tests: false
	}
	"l10n_mr": {
		dir: "addons/l10n_mr"
		depends: [
			"account",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_mt": {
		dir: "addons/l10n_mt"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_mt_pos": {
		dir: "addons/l10n_mt_pos"
		depends: [
			"point_of_sale",
		]
		has_tests: false
	}
	"l10n_mu_account": {
		dir: "addons/l10n_mu_account"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_mx": {
		dir: "addons/l10n_mx"
		depends: [
			"account",
		]
		has_tests: true
	}
	"l10n_my": {
		dir: "addons/l10n_my"
		depends: [
			"account",
			"account_tax_python",
		]
		has_tests: false
	}
	"l10n_my_edi": {
		dir: "addons/l10n_my_edi"
		depends: [
			"account_edi_proxy_client",
			"l10n_my",
			"l10n_my_ubl_pint",
		]
		has_tests: true
	}
	"l10n_my_edi_pos": {
		dir: "addons/l10n_my_edi_pos"
		depends: [
			"l10n_my_edi",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_my_ubl_pint": {
		dir: "addons/l10n_my_ubl_pint"
		depends: [
			"account_edi_ubl_cii",
		]
		has_tests: true
	}
	"l10n_mz": {
		dir: "addons/l10n_mz"
		depends: [
			"account",
			"base",
		]
		has_tests: false
	}
	"l10n_ne": {
		dir: "addons/l10n_ne"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_ng": {
		dir: "addons/l10n_ng"
		depends: [
			"account",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_nl": {
		dir: "addons/l10n_nl"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_no": {
		dir: "addons/l10n_no"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_nz": {
		dir: "addons/l10n_nz"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_om": {
		dir: "addons/l10n_om"
		depends: [
			"account",
			"l10n_gcc_invoice",
		]
		has_tests: false
	}
	"l10n_pa": {
		dir: "addons/l10n_pa"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_pe": {
		dir: "addons/l10n_pe"
		depends: [
			"account",
			"account_debit_note",
			"base_address_extended",
			"base_vat",
			"l10n_latam_base",
			"l10n_latam_invoice_document",
		]
		has_tests: false
	}
	"l10n_pe_pos": {
		dir: "addons/l10n_pe_pos"
		depends: [
			"l10n_pe",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_ph": {
		dir: "addons/l10n_ph"
		depends: [
			"account",
			"base_vat",
			"l10n_account_withholding_tax",
		]
		has_tests: true
	}
	"l10n_pk": {
		dir: "addons/l10n_pk"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_pl": {
		dir: "addons/l10n_pl"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_iban",
			"base_vat",
		]
		has_tests: true
	}
	"l10n_pl_bank_verification": {
		dir: "addons/l10n_pl_bank_verification"
		depends: [
			"l10n_pl",
		]
		has_tests: true
	}
	"l10n_pl_edi": {
		dir: "addons/l10n_pl_edi"
		depends: [
			"certificate",
			"l10n_pl",
		]
		has_tests: true
	}
	"l10n_pl_edi_jst": {
		dir: "addons/l10n_pl_edi_jst"
		depends: [
			"l10n_pl",
			"l10n_pl_edi",
		]
		has_tests: true
	}
	"l10n_pt": {
		dir: "addons/l10n_pt"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base",
			"base_vat",
		]
		has_tests: true
	}
	"l10n_qa": {
		dir: "addons/l10n_qa"
		depends: [
			"account",
			"l10n_gcc_invoice",
		]
		has_tests: false
	}
	"l10n_re": {
		dir: "addons/l10n_re"
		depends: [
			"account",
			"l10n_fr_account",
		]
		has_tests: false
	}
	"l10n_ro": {
		dir: "addons/l10n_ro"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_ro_cpv_code": {
		dir: "addons/l10n_ro_cpv_code"
		depends: [
			"l10n_ro_edi",
		]
		has_tests: true
	}
	"l10n_ro_edi": {
		dir: "addons/l10n_ro_edi"
		depends: [
			"account_edi_ubl_cii",
			"l10n_ro",
		]
		has_tests: true
	}
	"l10n_ro_edi_stock": {
		dir: "addons/l10n_ro_edi_stock"
		depends: [
			"l10n_ro_edi",
			"stock_delivery",
			"stock_picking_batch",
		]
		has_tests: true
	}
	"l10n_ro_edi_stock_batch": {
		dir: "addons/l10n_ro_edi_stock_batch"
		depends: [
			"l10n_ro_edi_stock",
			"stock_picking_batch",
		]
		has_tests: true
	}
	"l10n_rs": {
		dir: "addons/l10n_rs"
		depends: [
			"account",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_rs_edi": {
		dir: "addons/l10n_rs_edi"
		depends: [
			"account_edi_ubl_cii",
			"l10n_rs",
		]
		has_tests: true
	}
	"l10n_rw": {
		dir: "addons/l10n_rw"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_sa": {
		dir: "addons/l10n_sa"
		depends: [
			"account",
			"account_debit_note",
			"l10n_gcc_invoice",
		]
		has_tests: true
	}
	"l10n_sa_edi": {
		dir: "addons/l10n_sa_edi"
		depends: [
			"account_edi",
			"account_edi_ubl_cii",
			"base_vat",
			"certificate",
			"l10n_sa",
		]
		has_tests: true
	}
	"l10n_sa_edi_pos": {
		dir: "addons/l10n_sa_edi_pos"
		depends: [
			"l10n_sa_edi",
			"l10n_sa_pos",
		]
		has_tests: true
	}
	"l10n_sa_pos": {
		dir: "addons/l10n_sa_pos"
		depends: [
			"l10n_gcc_pos",
			"l10n_sa",
		]
		has_tests: true
	}
	"l10n_sa_withholding_tax": {
		dir: "addons/l10n_sa_withholding_tax"
		depends: [
			"l10n_account_withholding_tax",
			"l10n_sa",
		]
		has_tests: false
	}
	"l10n_se": {
		dir: "addons/l10n_se"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_sg": {
		dir: "addons/l10n_sg"
		depends: [
			"account",
			"account_qr_code_emv",
		]
		has_tests: true
	}
	"l10n_sg_ubl_pint": {
		dir: "addons/l10n_sg_ubl_pint"
		depends: [
			"account_edi_ubl_cii",
		]
		has_tests: true
	}
	"l10n_si": {
		dir: "addons/l10n_si"
		depends: [
			"account",
			"account_edi_ubl_cii",
			"base_vat",
		]
		has_tests: true
	}
	"l10n_sk": {
		dir: "addons/l10n_sk"
		depends: [
			"account",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_sn": {
		dir: "addons/l10n_sn"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_syscohada": {
		dir: "addons/l10n_syscohada"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_td": {
		dir: "addons/l10n_td"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_test_pos_qr_payment": {
		dir: "addons/l10n_test_pos_qr_payment"
		depends: [
			"account_qr_code_sepa",
			"l10n_be",
			"l10n_br",
			"l10n_ch",
			"l10n_hk",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_tg": {
		dir: "addons/l10n_tg"
		depends: [
			"account",
			"l10n_syscohada",
		]
		has_tests: false
	}
	"l10n_th": {
		dir: "addons/l10n_th"
		depends: [
			"account",
			"account_qr_code_emv",
		]
		has_tests: true
	}
	"l10n_tn": {
		dir: "addons/l10n_tn"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_tr": {
		dir: "addons/l10n_tr"
		depends: [
			"account",
		]
		has_tests: true
	}
	"l10n_tr_nilvera": {
		dir: "addons/l10n_tr_nilvera"
		depends: [
			"account_edi_ubl_cii",
			"l10n_tr",
		]
		has_tests: false
	}
	"l10n_tr_nilvera_base_vat": {
		dir: "addons/l10n_tr_nilvera_base_vat"
		depends: [
			"base_vat",
			"l10n_tr_nilvera",
		]
		has_tests: false
	}
	"l10n_tr_nilvera_edispatch": {
		dir: "addons/l10n_tr_nilvera_edispatch"
		depends: [
			"l10n_tr_nilvera",
			"stock",
			"stock_account",
		]
		has_tests: true
	}
	"l10n_tr_nilvera_einvoice": {
		dir: "addons/l10n_tr_nilvera_einvoice"
		depends: [
			"account_edi_ubl_cii",
			"l10n_tr_nilvera",
		]
		has_tests: true
	}
	"l10n_tr_nilvera_einvoice_extended": {
		dir: "addons/l10n_tr_nilvera_einvoice_extended"
		depends: [
			"contacts",
			"l10n_tr_nilvera_einvoice",
		]
		has_tests: true
	}
	"l10n_tw": {
		dir: "addons/l10n_tw"
		depends: [
			"account",
			"base_address_extended",
		]
		has_tests: false
	}
	"l10n_tw_edi_ecpay": {
		dir: "addons/l10n_tw_edi_ecpay"
		depends: [
			"base_vat",
			"l10n_tw",
		]
		has_tests: true
	}
	"l10n_tw_edi_ecpay_pos": {
		dir: "addons/l10n_tw_edi_ecpay_pos"
		depends: [
			"l10n_tw_edi_ecpay",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_tw_edi_ecpay_website_sale": {
		dir: "addons/l10n_tw_edi_ecpay_website_sale"
		depends: [
			"l10n_tw_edi_ecpay",
			"website_sale",
		]
		has_tests: true
	}
	"l10n_tz_account": {
		dir: "addons/l10n_tz_account"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_ua": {
		dir: "addons/l10n_ua"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_ug": {
		dir: "addons/l10n_ug"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_uk": {
		dir: "addons/l10n_uk"
		depends: [
			"account",
			"base_iban",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_us": {
		dir: "addons/l10n_us"
		depends: [
			"base",
		]
		has_tests: false
	}
	"l10n_us_account": {
		dir: "addons/l10n_us_account"
		depends: [
			"account",
			"l10n_us",
		]
		has_tests: false
	}
	"l10n_uy": {
		dir: "addons/l10n_uy"
		depends: [
			"account",
			"l10n_latam_base",
			"l10n_latam_invoice_document",
		]
		has_tests: true
	}
	"l10n_uy_pos": {
		dir: "addons/l10n_uy_pos"
		depends: [
			"l10n_uy",
			"point_of_sale",
		]
		has_tests: false
	}
	"l10n_uz": {
		dir: "addons/l10n_uz"
		depends: [
			"account",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_ve": {
		dir: "addons/l10n_ve"
		depends: [
			"account",
		]
		has_tests: false
	}
	"l10n_vn": {
		dir: "addons/l10n_vn"
		depends: [
			"account",
			"account_qr_code_emv",
			"base_iban",
		]
		has_tests: true
	}
	"l10n_vn_edi_viettel": {
		dir: "addons/l10n_vn_edi_viettel"
		depends: [
			"l10n_vn",
		]
		has_tests: true
	}
	"l10n_vn_edi_viettel_pos": {
		dir: "addons/l10n_vn_edi_viettel_pos"
		depends: [
			"l10n_vn_edi_viettel",
			"point_of_sale",
		]
		has_tests: true
	}
	"l10n_yt": {
		dir: "addons/l10n_yt"
		depends: [
			"account",
			"l10n_fr_account",
		]
		has_tests: false
	}
	"l10n_za": {
		dir: "addons/l10n_za"
		depends: [
			"account",
			"base_vat",
		]
		has_tests: false
	}
	"l10n_zm_account": {
		dir: "addons/l10n_zm_account"
		depends: [
			"account",
		]
		has_tests: false
	}
	"link_tracker": {
		dir: "addons/link_tracker"
		depends: [
			"mail",
			"utm",
		]
		has_tests: true
	}
	"loyalty": {
		dir: "addons/loyalty"
		depends: [
			"account",
			"portal",
			"product",
		]
		has_tests: true
	}
	"lunch": {
		dir: "addons/lunch"
		depends: [
			"mail",
		]
		has_tests: true
	}
	"mail": {
		dir: "addons/mail"
		depends: [
			"base",
			"base_setup",
			"bus",
			"html_editor",
			"web_tour",
		]
		has_tests: true
	}
	"mail_bot": {
		dir: "addons/mail_bot"
		depends: [
			"mail",
		]
		has_tests: false
	}
	"mail_bot_hr": {
		dir: "addons/mail_bot_hr"
		depends: [
			"hr",
			"mail_bot",
		]
		has_tests: false
	}
	"mail_group": {
		dir: "addons/mail_group"
		depends: [
			"mail",
			"portal",
		]
		has_tests: true
	}
	"mail_plugin": {
		dir: "addons/mail_plugin"
		depends: [
			"contacts",
			"iap",
			"web",
		]
		has_tests: true
	}
	"maintenance": {
		dir: "addons/maintenance"
		depends: [
			"mail",
		]
		has_tests: true
	}
	"marketing_card": {
		dir: "addons/marketing_card"
		depends: [
			"link_tracker",
			"mass_mailing",
			"website",
		]
		has_tests: true
	}
	"mass_mailing": {
		dir: "addons/mass_mailing"
		depends: [
			"contacts",
			"digest",
			"html_builder",
			"link_tracker",
			"mail",
			"social_media",
			"utm",
			"web_tour",
		]
		has_tests: true
	}
	"mass_mailing_crm": {
		dir: "addons/mass_mailing_crm"
		depends: [
			"crm",
			"mass_mailing",
		]
		has_tests: false
	}
	"mass_mailing_crm_sms": {
		dir: "addons/mass_mailing_crm_sms"
		depends: [
			"mass_mailing_crm",
			"mass_mailing_sms",
		]
		has_tests: false
	}
	"mass_mailing_event": {
		dir: "addons/mass_mailing_event"
		depends: [
			"event",
			"mass_mailing",
		]
		has_tests: false
	}
	"mass_mailing_event_sms": {
		dir: "addons/mass_mailing_event_sms"
		depends: [
			"event",
			"mass_mailing",
			"mass_mailing_event",
			"mass_mailing_sms",
			"sms",
		]
		has_tests: true
	}
	"mass_mailing_event_track": {
		dir: "addons/mass_mailing_event_track"
		depends: [
			"mass_mailing",
			"website_event_track",
		]
		has_tests: false
	}
	"mass_mailing_event_track_sms": {
		dir: "addons/mass_mailing_event_track_sms"
		depends: [
			"mass_mailing",
			"mass_mailing_sms",
			"sms",
			"website_event_track",
		]
		has_tests: false
	}
	"mass_mailing_sale": {
		dir: "addons/mass_mailing_sale"
		depends: [
			"mass_mailing",
			"sale",
		]
		has_tests: false
	}
	"mass_mailing_sale_sms": {
		dir: "addons/mass_mailing_sale_sms"
		depends: [
			"mass_mailing_sale",
			"mass_mailing_sms",
		]
		has_tests: false
	}
	"mass_mailing_slides": {
		dir: "addons/mass_mailing_slides"
		depends: [
			"mass_mailing",
			"website_slides",
		]
		has_tests: false
	}
	"mass_mailing_sms": {
		dir: "addons/mass_mailing_sms"
		depends: [
			"mass_mailing",
			"portal",
			"sms",
		]
		has_tests: true
	}
	"mass_mailing_themes": {
		dir: "addons/mass_mailing_themes"
		depends: [
			"mass_mailing",
		]
		has_tests: false
	}
	"microsoft_account": {
		dir: "addons/microsoft_account"
		depends: [
			"base_setup",
		]
		has_tests: false
	}
	"microsoft_calendar": {
		dir: "addons/microsoft_calendar"
		depends: [
			"calendar",
			"microsoft_account",
		]
		has_tests: true
	}
	"microsoft_outlook": {
		dir: "addons/microsoft_outlook"
		depends: [
			"mail",
		]
		has_tests: true
	}
	"mrp": {
		dir: "addons/mrp"
		depends: [
			"product",
			"resource",
			"stock",
		]
		has_tests: true
	}
	"mrp_account": {
		dir: "addons/mrp_account"
		depends: [
			"mrp",
			"stock_account",
		]
		has_tests: true
	}
	"mrp_landed_costs": {
		dir: "addons/mrp_landed_costs"
		depends: [
			"mrp",
			"stock_landed_costs",
		]
		has_tests: true
	}
	"mrp_product_expiry": {
		dir: "addons/mrp_product_expiry"
		depends: [
			"mrp",
			"product_expiry",
		]
		has_tests: true
	}
	"mrp_repair": {
		dir: "addons/mrp_repair"
		depends: [
			"mrp",
			"repair",
		]
		has_tests: true
	}
	"mrp_subcontracting": {
		dir: "addons/mrp_subcontracting"
		depends: [
			"mrp",
		]
		has_tests: true
	}
	"mrp_subcontracting_account": {
		dir: "addons/mrp_subcontracting_account"
		depends: [
			"mrp_account",
			"mrp_subcontracting",
		]
		has_tests: true
	}
	"mrp_subcontracting_dropshipping": {
		dir: "addons/mrp_subcontracting_dropshipping"
		depends: [
			"mrp_subcontracting",
			"stock_dropshipping",
		]
		has_tests: true
	}
	"mrp_subcontracting_landed_costs": {
		dir: "addons/mrp_subcontracting_landed_costs"
		depends: [
			"mrp_subcontracting",
			"stock_landed_costs",
		]
		has_tests: true
	}
	"mrp_subcontracting_purchase": {
		dir: "addons/mrp_subcontracting_purchase"
		depends: [
			"mrp_subcontracting",
			"purchase_mrp",
		]
		has_tests: true
	}
	"mrp_subcontracting_repair": {
		dir: "addons/mrp_subcontracting_repair"
		depends: [
			"mrp_subcontracting",
			"repair",
		]
		has_tests: false
	}
	"onboarding": {
		dir: "addons/onboarding"
		depends: [
			"web",
		]
		has_tests: true
	}
	"partner_autocomplete": {
		dir: "addons/partner_autocomplete"
		depends: [
			"iap_mail",
		]
		has_tests: true
	}
	"partnership": {
		dir: "addons/partnership"
		depends: [
			"crm",
			"sale",
		]
		has_tests: true
	}
	"payment": {
		dir: "addons/payment"
		depends: [
			"onboarding",
			"portal",
		]
		has_tests: true
	}
	"payment_adyen": {
		dir: "addons/payment_adyen"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_aps": {
		dir: "addons/payment_aps"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_asiapay": {
		dir: "addons/payment_asiapay"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_authorize": {
		dir: "addons/payment_authorize"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_buckaroo": {
		dir: "addons/payment_buckaroo"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_custom": {
		dir: "addons/payment_custom"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_demo": {
		dir: "addons/payment_demo"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_dpo": {
		dir: "addons/payment_dpo"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_ecpay": {
		dir: "addons/payment_ecpay"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_flutterwave": {
		dir: "addons/payment_flutterwave"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_iyzico": {
		dir: "addons/payment_iyzico"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_mercado_pago": {
		dir: "addons/payment_mercado_pago"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_mollie": {
		dir: "addons/payment_mollie"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_nuvei": {
		dir: "addons/payment_nuvei"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_paymob": {
		dir: "addons/payment_paymob"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_paypal": {
		dir: "addons/payment_paypal"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_payu": {
		dir: "addons/payment_payu"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_razorpay": {
		dir: "addons/payment_razorpay"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_redsys": {
		dir: "addons/payment_redsys"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_stripe": {
		dir: "addons/payment_stripe"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_toss_payments": {
		dir: "addons/payment_toss_payments"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_worldline": {
		dir: "addons/payment_worldline"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"payment_xendit": {
		dir: "addons/payment_xendit"
		depends: [
			"payment",
		]
		has_tests: true
	}
	"phone_validation": {
		dir: "addons/phone_validation"
		depends: [
			"base",
			"mail",
		]
		has_tests: true
	}
	"point_of_sale": {
		dir: "addons/point_of_sale"
		depends: [
			"barcodes",
			"digest",
			"google_address_autocomplete",
			"html_editor",
			"iot_base",
			"partner_autocomplete",
			"phone_validation",
			"resource",
			"stock_account",
		]
		has_tests: true
	}
	"portal": {
		dir: "addons/portal"
		depends: [
			"auth_signup",
			"html_editor",
			"http_routing",
			"mail",
			"web",
		]
		has_tests: true
	}
	"portal_rating": {
		dir: "addons/portal_rating"
		depends: [
			"portal",
			"rating",
		]
		has_tests: false
	}
	"pos_account_tax_python": {
		dir: "addons/pos_account_tax_python"
		depends: [
			"account_tax_python",
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_adyen": {
		dir: "addons/pos_adyen"
		depends: [
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_cashdro": {
		dir: "addons/pos_cashdro"
		depends: [
			"point_of_sale",
		]
		has_tests: false
	}
	"pos_cashmatic": {
		dir: "addons/pos_cashmatic"
		depends: [
			"point_of_sale",
		]
		has_tests: false
	}
	"pos_discount": {
		dir: "addons/pos_discount"
		depends: [
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_dpopay": {
		dir: "addons/pos_dpopay"
		depends: [
			"point_of_sale",
		]
		has_tests: false
	}
	"pos_edi_ubl": {
		dir: "addons/pos_edi_ubl"
		depends: [
			"account_edi_ubl_cii",
			"point_of_sale",
		]
		has_tests: false
	}
	"pos_event": {
		dir: "addons/pos_event"
		depends: [
			"event_product",
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_event_sale": {
		dir: "addons/pos_event_sale"
		depends: [
			"pos_event",
			"pos_sale",
		]
		has_tests: true
	}
	"pos_glory_cash": {
		dir: "addons/pos_glory_cash"
		depends: [
			"point_of_sale",
		]
		has_tests: false
	}
	"pos_hr": {
		dir: "addons/pos_hr"
		depends: [
			"hr",
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_hr_restaurant": {
		dir: "addons/pos_hr_restaurant"
		depends: [
			"pos_hr",
			"pos_restaurant",
		]
		has_tests: true
	}
	"pos_imin": {
		dir: "addons/pos_imin"
		depends: [
			"point_of_sale",
		]
		has_tests: false
	}
	"pos_loyalty": {
		dir: "addons/pos_loyalty"
		depends: [
			"loyalty",
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_mercado_pago": {
		dir: "addons/pos_mercado_pago"
		depends: [
			"point_of_sale",
		]
		has_tests: false
	}
	"pos_mollie": {
		dir: "addons/pos_mollie"
		depends: [
			"payment_mollie",
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_mrp": {
		dir: "addons/pos_mrp"
		depends: [
			"mrp",
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_online_payment": {
		dir: "addons/pos_online_payment"
		depends: [
			"account_payment",
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_online_payment_self_order": {
		dir: "addons/pos_online_payment_self_order"
		depends: [
			"pos_online_payment",
			"pos_self_order",
		]
		has_tests: true
	}
	"pos_pine_labs": {
		dir: "addons/pos_pine_labs"
		depends: [
			"point_of_sale",
		]
		has_tests: false
	}
	"pos_qfpay": {
		dir: "addons/pos_qfpay"
		depends: [
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_razorpay": {
		dir: "addons/pos_razorpay"
		depends: [
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_repair": {
		dir: "addons/pos_repair"
		depends: [
			"point_of_sale",
			"repair",
		]
		has_tests: true
	}
	"pos_restaurant": {
		dir: "addons/pos_restaurant"
		depends: [
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_restaurant_adyen": {
		dir: "addons/pos_restaurant_adyen"
		depends: [
			"payment_adyen",
			"pos_adyen",
			"pos_restaurant",
		]
		has_tests: false
	}
	"pos_restaurant_loyalty": {
		dir: "addons/pos_restaurant_loyalty"
		depends: [
			"pos_loyalty",
			"pos_restaurant",
		]
		has_tests: true
	}
	"pos_restaurant_stripe": {
		dir: "addons/pos_restaurant_stripe"
		depends: [
			"payment_stripe",
			"pos_restaurant",
			"pos_stripe",
		]
		has_tests: false
	}
	"pos_safaricom": {
		dir: "addons/pos_safaricom"
		depends: [
			"point_of_sale",
		]
		has_tests: true
	}
	"pos_sale": {
		dir: "addons/pos_sale"
		depends: [
			"point_of_sale",
			"sale_management",
		]
		has_tests: true
	}
	"pos_sale_loyalty": {
		dir: "addons/pos_sale_loyalty"
		depends: [
			"pos_loyalty",
			"pos_sale",
		]
		has_tests: true
	}
	"pos_sale_margin": {
		dir: "addons/pos_sale_margin"
		depends: [
			"pos_sale",
			"sale_margin",
		]
		has_tests: true
	}
	"pos_self_order": {
		dir: "addons/pos_self_order"
		depends: [
			"http_routing",
			"link_tracker",
			"pos_restaurant",
		]
		has_tests: true
	}
	"pos_self_order_adyen": {
		dir: "addons/pos_self_order_adyen"
		depends: [
			"pos_adyen",
			"pos_self_order",
		]
		has_tests: false
	}
	"pos_self_order_pine_labs": {
		dir: "addons/pos_self_order_pine_labs"
		depends: [
			"pos_pine_labs",
			"pos_self_order",
		]
		has_tests: false
	}
	"pos_self_order_qfpay": {
		dir: "addons/pos_self_order_qfpay"
		depends: [
			"pos_qfpay",
			"pos_self_order",
		]
		has_tests: true
	}
	"pos_self_order_razorpay": {
		dir: "addons/pos_self_order_razorpay"
		depends: [
			"pos_razorpay",
			"pos_self_order",
		]
		has_tests: false
	}
	"pos_self_order_sale": {
		dir: "addons/pos_self_order_sale"
		depends: [
			"pos_sale",
			"pos_self_order",
		]
		has_tests: false
	}
	"pos_self_order_stripe": {
		dir: "addons/pos_self_order_stripe"
		depends: [
			"pos_self_order",
			"pos_stripe",
		]
		has_tests: true
	}
	"pos_self_order_viva_com": {
		dir: "addons/pos_self_order_viva_com"
		depends: [
			"pos_self_order",
			"pos_viva_com",
		]
		has_tests: false
	}
	"pos_sms": {
		dir: "addons/pos_sms"
		depends: [
			"point_of_sale",
			"sms",
		]
		has_tests: true
	}
	"pos_stripe": {
		dir: "addons/pos_stripe"
		depends: [
			"payment_stripe",
			"point_of_sale",
		]
		has_tests: false
	}
	"pos_viva_com": {
		dir: "addons/pos_viva_com"
		depends: [
			"point_of_sale",
		]
		has_tests: true
	}
	"privacy_lookup": {
		dir: "addons/privacy_lookup"
		depends: [
			"mail",
		]
		has_tests: true
	}
	"product": {
		dir: "addons/product"
		depends: [
			"base",
			"mail",
			"uom",
		]
		has_tests: true
	}
	"product_email_template": {
		dir: "addons/product_email_template"
		depends: [
			"account",
		]
		has_tests: true
	}
	"product_expiry": {
		dir: "addons/product_expiry"
		depends: [
			"stock",
		]
		has_tests: true
	}
	"product_margin": {
		dir: "addons/product_margin"
		depends: [
			"account",
		]
		has_tests: true
	}
	"product_matrix": {
		dir: "addons/product_matrix"
		depends: [
			"account",
		]
		has_tests: true
	}
	"project": {
		dir: "addons/project"
		depends: [
			"analytic",
			"base_setup",
			"digest",
			"mail",
			"portal",
			"rating",
			"resource",
			"web",
			"web_tour",
		]
		has_tests: true
	}
	"project_account": {
		dir: "addons/project_account"
		depends: [
			"account",
			"project",
		]
		has_tests: true
	}
	"project_hr_expense": {
		dir: "addons/project_hr_expense"
		depends: [
			"hr_expense",
			"project_account",
		]
		has_tests: true
	}
	"project_hr_skills": {
		dir: "addons/project_hr_skills"
		depends: [
			"hr_skills",
			"project",
		]
		has_tests: false
	}
	"project_mail_plugin": {
		dir: "addons/project_mail_plugin"
		depends: [
			"mail_plugin",
			"project",
		]
		has_tests: true
	}
	"project_mrp": {
		dir: "addons/project_mrp"
		depends: [
			"mrp",
			"project",
		]
		has_tests: false
	}
	"project_mrp_account": {
		dir: "addons/project_mrp_account"
		depends: [
			"mrp_account",
			"project_mrp",
		]
		has_tests: true
	}
	"project_mrp_sale": {
		dir: "addons/project_mrp_sale"
		depends: [
			"project_mrp",
			"sale_mrp",
			"sale_project",
		]
		has_tests: true
	}
	"project_mrp_stock_landed_costs": {
		dir: "addons/project_mrp_stock_landed_costs"
		depends: [
			"mrp_landed_costs",
			"project_mrp_account",
		]
		has_tests: false
	}
	"project_purchase": {
		dir: "addons/project_purchase"
		depends: [
			"project_account",
			"purchase",
		]
		has_tests: true
	}
	"project_purchase_stock": {
		dir: "addons/project_purchase_stock"
		depends: [
			"project_purchase",
			"project_stock",
		]
		has_tests: true
	}
	"project_sale_expense": {
		dir: "addons/project_sale_expense"
		depends: [
			"project_hr_expense",
			"sale_expense",
			"sale_project",
		]
		has_tests: true
	}
	"project_sms": {
		dir: "addons/project_sms"
		depends: [
			"project",
			"sms",
		]
		has_tests: true
	}
	"project_stock": {
		dir: "addons/project_stock"
		depends: [
			"project",
			"stock",
		]
		has_tests: false
	}
	"project_stock_account": {
		dir: "addons/project_stock_account"
		depends: [
			"project_stock",
			"stock_account",
		]
		has_tests: true
	}
	"project_stock_landed_costs": {
		dir: "addons/project_stock_landed_costs"
		depends: [
			"project_stock_account",
			"stock_landed_costs",
		]
		has_tests: false
	}
	"project_timesheet_holidays": {
		dir: "addons/project_timesheet_holidays"
		depends: [
			"hr_holidays",
			"hr_timesheet",
		]
		has_tests: true
	}
	"project_todo": {
		dir: "addons/project_todo"
		depends: [
			"project",
		]
		has_tests: true
	}
	"purchase": {
		dir: "addons/purchase"
		depends: [
			"account",
		]
		has_tests: true
	}
	"purchase_edi_ubl_bis3": {
		dir: "addons/purchase_edi_ubl_bis3"
		depends: [
			"account_edi_ubl_cii",
			"purchase",
		]
		has_tests: true
	}
	"purchase_mrp": {
		dir: "addons/purchase_mrp"
		depends: [
			"mrp",
			"purchase_stock",
		]
		has_tests: true
	}
	"purchase_product_matrix": {
		dir: "addons/purchase_product_matrix"
		depends: [
			"product_matrix",
			"purchase",
		]
		has_tests: true
	}
	"purchase_repair": {
		dir: "addons/purchase_repair"
		depends: [
			"purchase_stock",
			"repair",
		]
		has_tests: true
	}
	"purchase_requisition": {
		dir: "addons/purchase_requisition"
		depends: [
			"purchase",
		]
		has_tests: true
	}
	"purchase_requisition_sale": {
		dir: "addons/purchase_requisition_sale"
		depends: [
			"purchase_requisition",
			"sale_purchase",
		]
		has_tests: true
	}
	"purchase_requisition_stock": {
		dir: "addons/purchase_requisition_stock"
		depends: [
			"purchase_requisition",
			"purchase_stock",
		]
		has_tests: true
	}
	"purchase_stock": {
		dir: "addons/purchase_stock"
		depends: [
			"purchase",
			"stock_account",
		]
		has_tests: true
	}
	"rating": {
		dir: "addons/rating"
		depends: [
			"mail",
		]
		has_tests: true
	}
	"repair": {
		dir: "addons/repair"
		depends: [
			"sale_management",
			"sale_stock",
		]
		has_tests: true
	}
	"resource": {
		dir: "addons/resource"
		depends: [
			"base",
			"web",
		]
		has_tests: true
	}
	"resource_mail": {
		dir: "addons/resource_mail"
		depends: [
			"mail",
			"resource",
		]
		has_tests: false
	}
	"rpc": {
		dir: "addons/rpc"
		depends: [
			"base",
		]
		has_tests: true
	}
	"sale": {
		dir: "addons/sale"
		depends: [
			"account_payment",
			"sales_team",
			"utm",
		]
		has_tests: true
	}
	"sale_crm": {
		dir: "addons/sale_crm"
		depends: [
			"crm",
			"sale",
		]
		has_tests: true
	}
	"sale_edi_ubl": {
		dir: "addons/sale_edi_ubl"
		depends: [
			"account_edi_ubl_cii",
			"sale",
		]
		has_tests: true
	}
	"sale_expense": {
		dir: "addons/sale_expense"
		depends: [
			"hr_expense",
			"sale_management",
		]
		has_tests: true
	}
	"sale_expense_margin": {
		dir: "addons/sale_expense_margin"
		depends: [
			"sale_expense",
			"sale_margin",
		]
		has_tests: true
	}
	"sale_gelato": {
		dir: "addons/sale_gelato"
		depends: [
			"delivery",
			"sale",
		]
		has_tests: true
	}
	"sale_gelato_stock": {
		dir: "addons/sale_gelato_stock"
		depends: [
			"sale_gelato",
			"sale_stock",
		]
		has_tests: false
	}
	"sale_loyalty": {
		dir: "addons/sale_loyalty"
		depends: [
			"loyalty",
			"sale",
		]
		has_tests: true
	}
	"sale_loyalty_delivery": {
		dir: "addons/sale_loyalty_delivery"
		depends: [
			"delivery",
			"sale_loyalty",
		]
		has_tests: true
	}
	"sale_management": {
		dir: "addons/sale_management"
		depends: [
			"digest",
			"sale",
		]
		has_tests: true
	}
	"sale_margin": {
		dir: "addons/sale_margin"
		depends: [
			"sale_management",
		]
		has_tests: true
	}
	"sale_mrp": {
		dir: "addons/sale_mrp"
		depends: [
			"mrp",
			"sale_stock",
		]
		has_tests: true
	}
	"sale_mrp_margin": {
		dir: "addons/sale_mrp_margin"
		depends: [
			"sale_mrp",
			"sale_stock_margin",
		]
		has_tests: true
	}
	"sale_pdf_quote_builder": {
		dir: "addons/sale_pdf_quote_builder"
		depends: [
			"sale_management",
		]
		has_tests: true
	}
	"sale_product_matrix": {
		dir: "addons/sale_product_matrix"
		depends: [
			"product_matrix",
			"sale",
		]
		has_tests: false
	}
	"sale_project": {
		dir: "addons/sale_project"
		depends: [
			"project_account",
			"sale_management",
			"sale_service",
		]
		has_tests: true
	}
	"sale_project_stock": {
		dir: "addons/sale_project_stock"
		depends: [
			"project_stock_account",
			"sale_project",
			"sale_stock",
		]
		has_tests: true
	}
	"sale_project_stock_account": {
		dir: "addons/sale_project_stock_account"
		depends: [
			"project_stock_account",
			"sale_project",
		]
		has_tests: true
	}
	"sale_purchase": {
		dir: "addons/sale_purchase"
		depends: [
			"purchase",
			"sale",
		]
		has_tests: true
	}
	"sale_purchase_project": {
		dir: "addons/sale_purchase_project"
		depends: [
			"project_purchase",
			"sale_project",
			"sale_purchase",
		]
		has_tests: true
	}
	"sale_purchase_stock": {
		dir: "addons/sale_purchase_stock"
		depends: [
			"purchase_stock",
			"sale_purchase",
			"sale_stock",
		]
		has_tests: true
	}
	"sale_service": {
		dir: "addons/sale_service"
		depends: [
			"sale_management",
		]
		has_tests: false
	}
	"sale_sms": {
		dir: "addons/sale_sms"
		depends: [
			"sale",
			"sms",
		]
		has_tests: false
	}
	"sale_stock": {
		dir: "addons/sale_stock"
		depends: [
			"sale",
			"stock_account",
		]
		has_tests: true
	}
	"sale_stock_margin": {
		dir: "addons/sale_stock_margin"
		depends: [
			"sale_margin",
			"sale_stock",
		]
		has_tests: true
	}
	"sale_stock_product_expiry": {
		dir: "addons/sale_stock_product_expiry"
		depends: [
			"product_expiry",
			"sale_stock",
		]
		has_tests: true
	}
	"sale_timesheet": {
		dir: "addons/sale_timesheet"
		depends: [
			"hr_timesheet",
			"sale_project",
		]
		has_tests: true
	}
	"sale_timesheet_margin": {
		dir: "addons/sale_timesheet_margin"
		depends: [
			"sale_margin",
			"sale_timesheet",
		]
		has_tests: true
	}
	"sales_team": {
		dir: "addons/sales_team"
		depends: [
			"base",
			"mail",
		]
		has_tests: true
	}
	"sms": {
		dir: "addons/sms"
		depends: [
			"base",
			"iap_mail",
			"mail",
			"phone_validation",
		]
		has_tests: true
	}
	"sms_twilio": {
		dir: "addons/sms_twilio"
		depends: [
			"sms",
		]
		has_tests: true
	}
	"snailmail": {
		dir: "addons/snailmail"
		depends: [
			"iap_mail",
			"mail",
		]
		has_tests: true
	}
	"snailmail_account": {
		dir: "addons/snailmail_account"
		depends: [
			"account",
			"snailmail",
		]
		has_tests: true
	}
	"social_media": {
		dir: "addons/social_media"
		depends: [
			"base",
		]
		has_tests: false
	}
	"spreadsheet": {
		dir: "addons/spreadsheet"
		depends: [
			"bus",
			"portal",
			"web",
		]
		has_tests: true
	}
	"spreadsheet_account": {
		dir: "addons/spreadsheet_account"
		depends: [
			"account",
			"spreadsheet",
		]
		has_tests: true
	}
	"spreadsheet_dashboard": {
		dir: "addons/spreadsheet_dashboard"
		depends: [
			"spreadsheet",
		]
		has_tests: true
	}
	"spreadsheet_dashboard_account": {
		dir: "addons/spreadsheet_dashboard_account"
		depends: [
			"account",
			"spreadsheet_dashboard",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_event_sale": {
		dir: "addons/spreadsheet_dashboard_event_sale"
		depends: [
			"event_sale",
			"spreadsheet_dashboard",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_hr_expense": {
		dir: "addons/spreadsheet_dashboard_hr_expense"
		depends: [
			"sale_expense",
			"spreadsheet_dashboard",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_hr_timesheet": {
		dir: "addons/spreadsheet_dashboard_hr_timesheet"
		depends: [
			"hr_timesheet",
			"spreadsheet_dashboard",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_im_livechat": {
		dir: "addons/spreadsheet_dashboard_im_livechat"
		depends: [
			"im_livechat",
			"spreadsheet_dashboard",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_pos_hr": {
		dir: "addons/spreadsheet_dashboard_pos_hr"
		depends: [
			"pos_hr",
			"spreadsheet_dashboard",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_pos_restaurant": {
		dir: "addons/spreadsheet_dashboard_pos_restaurant"
		depends: [
			"pos_hr",
			"pos_restaurant",
			"spreadsheet_dashboard",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_sale": {
		dir: "addons/spreadsheet_dashboard_sale"
		depends: [
			"sale",
			"spreadsheet_dashboard",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_sale_timesheet": {
		dir: "addons/spreadsheet_dashboard_sale_timesheet"
		depends: [
			"sale_timesheet",
			"spreadsheet_dashboard",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_stock_account": {
		dir: "addons/spreadsheet_dashboard_stock_account"
		depends: [
			"spreadsheet_dashboard",
			"stock_account",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_website_sale": {
		dir: "addons/spreadsheet_dashboard_website_sale"
		depends: [
			"spreadsheet_dashboard",
			"website_sale",
		]
		has_tests: false
	}
	"spreadsheet_dashboard_website_sale_slides": {
		dir: "addons/spreadsheet_dashboard_website_sale_slides"
		depends: [
			"spreadsheet_dashboard",
			"website_sale_slides",
		]
		has_tests: false
	}
	"stock": {
		dir: "addons/stock"
		depends: [
			"barcodes_gs1_nomenclature",
			"digest",
			"product",
		]
		has_tests: true
	}
	"stock_account": {
		dir: "addons/stock_account"
		depends: [
			"account",
			"stock",
		]
		has_tests: true
	}
	"stock_delivery": {
		dir: "addons/stock_delivery"
		depends: [
			"delivery",
			"sale_stock",
		]
		has_tests: true
	}
	"stock_dropshipping": {
		dir: "addons/stock_dropshipping"
		depends: [
			"sale_purchase_stock",
		]
		has_tests: true
	}
	"stock_fleet": {
		dir: "addons/stock_fleet"
		depends: [
			"fleet",
			"stock_picking_batch",
		]
		has_tests: false
	}
	"stock_landed_costs": {
		dir: "addons/stock_landed_costs"
		depends: [
			"purchase_stock",
			"stock_account",
		]
		has_tests: true
	}
	"stock_maintenance": {
		dir: "addons/stock_maintenance"
		depends: [
			"maintenance",
			"stock",
		]
		has_tests: false
	}
	"stock_picking_batch": {
		dir: "addons/stock_picking_batch"
		depends: [
			"stock",
		]
		has_tests: true
	}
	"stock_sms": {
		dir: "addons/stock_sms"
		depends: [
			"sms",
			"stock",
		]
		has_tests: false
	}
	"survey": {
		dir: "addons/survey"
		depends: [
			"auth_signup",
			"gamification",
			"http_routing",
			"mail",
			"web_tour",
		]
		has_tests: true
	}
	"survey_crm": {
		dir: "addons/survey_crm"
		depends: [
			"crm",
			"survey",
		]
		has_tests: true
	}
	"test_access_rights": {
		dir: "odoo/addons/test_access_rights"
		depends: []
		has_tests: true
	}
	"test_action_bindings": {
		dir: "odoo/addons/test_action_bindings"
		depends: []
		has_tests: true
	}
	"test_assetsbundle": {
		dir: "odoo/addons/test_assetsbundle"
		depends: [
			"base",
		]
		has_tests: true
	}
	"test_auth_custom": {
		dir: "odoo/addons/test_auth_custom"
		depends: []
		has_tests: true
	}
	"test_base_automation": {
		dir: "addons/test_base_automation"
		depends: [
			"base_automation",
		]
		has_tests: true
	}
	"test_convert": {
		dir: "odoo/addons/test_convert"
		depends: []
		has_tests: true
	}
	"test_converter": {
		dir: "odoo/addons/test_converter"
		depends: [
			"base",
		]
		has_tests: true
	}
	"test_crm_full": {
		dir: "addons/test_crm_full"
		depends: [
			"crm",
			"crm_iap_enrich",
			"crm_iap_mine",
			"crm_sms",
			"event_crm",
			"sale_crm",
			"website_crm",
			"website_crm_iap_reveal",
			"website_crm_livechat",
			"website_crm_partner_assign",
		]
		has_tests: true
	}
	"test_data_module": {
		dir: "odoo/addons/test_data_module"
		depends: []
		has_tests: false
	}
	"test_data_module_install": {
		dir: "odoo/addons/test_data_module_install"
		depends: [
			"test_data_module",
		]
		has_tests: true
	}
	"test_discuss_full": {
		dir: "addons/test_discuss_full"
		depends: [
			"calendar",
			"crm",
			"crm_livechat",
			"hr_attendance",
			"hr_fleet",
			"hr_holidays",
			"hr_homeworking",
			"im_livechat",
			"mail",
			"mail_bot",
			"project_todo",
			"website_livechat",
			"website_sale",
			"website_slides",
		]
		has_tests: true
	}
	"test_event_full": {
		dir: "addons/test_event_full"
		depends: [
			"event",
			"event_booth",
			"event_crm",
			"event_crm_sale",
			"event_sale",
			"event_sms",
			"payment_demo",
			"website_event_booth_sale_exhibitor",
			"website_event_exhibitor",
			"website_event_sale",
			"website_event_track",
			"website_event_track_live",
			"website_event_track_quiz",
		]
		has_tests: true
	}
	"test_html_field_history": {
		dir: "addons/test_html_field_history"
		depends: [
			"html_editor",
		]
		has_tests: true
	}
	"test_http": {
		dir: "odoo/addons/test_http"
		depends: [
			"mail",
			"rpc",
			"web",
			"web_tour",
		]
		has_tests: true
	}
	"test_import_export": {
		dir: "addons/test_import_export"
		depends: [
			"base_import",
			"web",
			"website",
		]
		has_tests: true
	}
	"test_inherit": {
		dir: "odoo/addons/test_inherit"
		depends: [
			"base",
			"test_orm",
		]
		has_tests: true
	}
	"test_inherit_depends": {
		dir: "odoo/addons/test_inherit_depends"
		depends: [
			"test_inherit",
			"test_orm",
		]
		has_tests: true
	}
	"test_inherits": {
		dir: "odoo/addons/test_inherits"
		depends: [
			"base",
		]
		has_tests: true
	}
	"test_inherits_depends": {
		dir: "odoo/addons/test_inherits_depends"
		depends: [
			"test_inherits",
		]
		has_tests: true
	}
	"test_lint": {
		dir: "odoo/addons/test_lint"
		depends: [
			"base",
		]
		has_tests: true
	}
	"test_mail": {
		dir: "addons/test_mail"
		depends: [
			"mail",
			"test_orm",
		]
		has_tests: true
	}
	"test_mail_full": {
		dir: "addons/test_mail_full"
		depends: [
			"mail",
			"mail_bot",
			"mass_mailing",
			"mass_mailing_sms",
			"phone_validation",
			"portal",
			"rating",
			"sms",
			"test_mail",
			"test_mail_sms",
			"test_mass_mailing",
		]
		has_tests: true
	}
	"test_mail_sms": {
		dir: "addons/test_mail_sms"
		depends: [
			"mail",
			"sms",
			"sms_twilio",
			"test_orm",
		]
		has_tests: true
	}
	"test_main_flows": {
		dir: "odoo/addons/test_main_flows"
		depends: [
			"account",
			"crm",
			"mrp",
			"purchase_stock",
			"sale_timesheet",
			"web_tour",
		]
		has_tests: true
	}
	"test_mass_mailing": {
		dir: "addons/test_mass_mailing"
		depends: [
			"mass_mailing",
			"mass_mailing_sms",
			"sms_twilio",
			"test_mail",
			"test_mail_sms",
		]
		has_tests: true
	}
	"test_mimetypes": {
		dir: "odoo/addons/test_mimetypes"
		depends: []
		has_tests: true
	}
	"test_orm": {
		dir: "odoo/addons/test_orm"
		depends: [
			"base",
			"web",
			"web_tour",
		]
		has_tests: true
	}
	"test_read_group": {
		dir: "odoo/addons/test_read_group"
		depends: [
			"base",
			"web",
		]
		has_tests: true
	}
	"test_resource": {
		dir: "addons/test_resource"
		depends: [
			"resource",
		]
		has_tests: true
	}
	"test_rpc": {
		dir: "odoo/addons/test_rpc"
		depends: [
			"rpc",
			"web",
		]
		has_tests: true
	}
	"test_sale_product_configurators": {
		dir: "addons/test_sale_product_configurators"
		depends: [
			"event_sale",
			"sale_management",
			"sale_product_matrix",
		]
		has_tests: true
	}
	"test_sale_purchase_edi_ubl": {
		dir: "addons/test_sale_purchase_edi_ubl"
		depends: [
			"purchase_edi_ubl_bis3",
			"sale_edi_ubl",
		]
		has_tests: true
	}
	"test_search_panel": {
		dir: "odoo/addons/test_search_panel"
		depends: [
			"web",
		]
		has_tests: true
	}
	"test_spreadsheet": {
		dir: "addons/test_spreadsheet"
		depends: [
			"spreadsheet",
		]
		has_tests: true
	}
	"test_testing_utilities": {
		dir: "odoo/addons/test_testing_utilities"
		depends: [
			"base",
			"web",
		]
		has_tests: true
	}
	"test_translation_import": {
		dir: "odoo/addons/test_translation_import"
		depends: [
			"base",
		]
		has_tests: true
	}
	"test_uninstall": {
		dir: "odoo/addons/test_uninstall"
		depends: [
			"base",
		]
		has_tests: false
	}
	"test_website": {
		dir: "addons/test_website"
		depends: [
			"theme_default",
			"web_unsplash",
			"website",
		]
		has_tests: true
	}
	"test_website_modules": {
		dir: "addons/test_website_modules"
		depends: [
			"theme_default",
			"website",
			"website_blog",
			"website_crm_iap_reveal",
			"website_event_sale",
			"website_livechat",
			"website_sale_comparison",
			"website_sale_wishlist",
			"website_slides",
		]
		has_tests: true
	}
	"test_website_slides_full": {
		dir: "addons/test_website_slides_full"
		depends: [
			"website_sale_slides",
			"website_slides_forum",
			"website_slides_survey",
		]
		has_tests: true
	}
	"theme_default": {
		dir: "addons/theme_default"
		depends: [
			"website",
		]
		has_tests: false
	}
	"transifex": {
		dir: "addons/transifex"
		depends: [
			"base",
			"web",
		]
		has_tests: false
	}
	"uom": {
		dir: "addons/uom"
		depends: [
			"base",
		]
		has_tests: true
	}
	"utm": {
		dir: "addons/utm"
		depends: [
			"base",
			"web",
		]
		has_tests: true
	}
	"web": {
		dir: "addons/web"
		depends: [
			"base",
		]
		has_tests: true
	}
	"web_hierarchy": {
		dir: "addons/web_hierarchy"
		depends: [
			"web",
		]
		has_tests: false
	}
	"web_tour": {
		dir: "addons/web_tour"
		depends: [
			"web",
		]
		has_tests: true
	}
	"web_unsplash": {
		dir: "addons/web_unsplash"
		depends: [
			"base_setup",
			"html_editor",
		]
		has_tests: true
	}
	"website": {
		dir: "addons/website"
		depends: [
			"auth_signup",
			"digest",
			"google_recaptcha",
			"html_builder",
			"html_editor",
			"http_routing",
			"mail",
			"portal",
			"social_media",
			"utm",
			"web",
		]
		has_tests: true
	}
	"website_blog": {
		dir: "addons/website_blog"
		depends: [
			"html_builder",
			"website_mail",
			"website_partner",
		]
		has_tests: true
	}
	"website_cf_turnstile": {
		dir: "addons/website_cf_turnstile"
		depends: [
			"website",
		]
		has_tests: false
	}
	"website_crm": {
		dir: "addons/website_crm"
		depends: [
			"crm",
			"website",
		]
		has_tests: true
	}
	"website_crm_iap_reveal": {
		dir: "addons/website_crm_iap_reveal"
		depends: [
			"crm_iap_mine",
			"iap_crm",
			"iap_mail",
			"website_crm",
		]
		has_tests: true
	}
	"website_crm_livechat": {
		dir: "addons/website_crm_livechat"
		depends: [
			"website_crm",
			"website_livechat",
		]
		has_tests: false
	}
	"website_crm_partner_assign": {
		dir: "addons/website_crm_partner_assign"
		depends: [
			"account",
			"base_geolocalize",
			"crm",
			"partnership",
			"portal",
			"website_google_map",
			"website_partner",
		]
		has_tests: true
	}
	"website_crm_sms": {
		dir: "addons/website_crm_sms"
		depends: [
			"crm",
			"website_sms",
		]
		has_tests: true
	}
	"website_customer": {
		dir: "addons/website_customer"
		depends: [
			"website_crm_partner_assign",
			"website_google_map",
			"website_partner",
		]
		has_tests: true
	}
	"website_event": {
		dir: "addons/website_event"
		depends: [
			"event",
			"html_builder",
			"website",
			"website_mail",
			"website_partner",
		]
		has_tests: true
	}
	"website_event_booth": {
		dir: "addons/website_event_booth"
		depends: [
			"event_booth",
			"website_event",
		]
		has_tests: false
	}
	"website_event_booth_exhibitor": {
		dir: "addons/website_event_booth_exhibitor"
		depends: [
			"website_event_booth",
			"website_event_exhibitor",
		]
		has_tests: true
	}
	"website_event_booth_sale": {
		dir: "addons/website_event_booth_sale"
		depends: [
			"event_booth_sale",
			"website_event_booth",
			"website_sale",
		]
		has_tests: true
	}
	"website_event_booth_sale_exhibitor": {
		dir: "addons/website_event_booth_sale_exhibitor"
		depends: [
			"website_event_booth_sale",
			"website_event_exhibitor",
		]
		has_tests: false
	}
	"website_event_crm": {
		dir: "addons/website_event_crm"
		depends: [
			"event_crm",
			"website_event",
		]
		has_tests: true
	}
	"website_event_exhibitor": {
		dir: "addons/website_event_exhibitor"
		depends: [
			"website_event",
		]
		has_tests: true
	}
	"website_event_sale": {
		dir: "addons/website_event_sale"
		depends: [
			"event_sale",
			"website_event",
			"website_sale",
		]
		has_tests: true
	}
	"website_event_track": {
		dir: "addons/website_event_track"
		depends: [
			"website_event",
		]
		has_tests: true
	}
	"website_event_track_live": {
		dir: "addons/website_event_track_live"
		depends: [
			"website_event_track",
		]
		has_tests: false
	}
	"website_event_track_live_quiz": {
		dir: "addons/website_event_track_live_quiz"
		depends: [
			"website_event_track_live",
			"website_event_track_quiz",
		]
		has_tests: false
	}
	"website_event_track_quiz": {
		dir: "addons/website_event_track_quiz"
		depends: [
			"website_event_track",
			"website_profile",
		]
		has_tests: false
	}
	"website_forum": {
		dir: "addons/website_forum"
		depends: [
			"auth_signup",
			"website_mail",
			"website_profile",
		]
		has_tests: true
	}
	"website_google_map": {
		dir: "addons/website_google_map"
		depends: [
			"base_geolocalize",
			"website_partner",
		]
		has_tests: false
	}
	"website_hr_recruitment": {
		dir: "addons/website_hr_recruitment"
		depends: [
			"hr_recruitment",
			"website_mail",
		]
		has_tests: true
	}
	"website_hr_recruitment_livechat": {
		dir: "addons/website_hr_recruitment_livechat"
		depends: [
			"im_livechat",
			"website_hr_recruitment",
		]
		has_tests: false
	}
	"website_links": {
		dir: "addons/website_links"
		depends: [
			"link_tracker",
			"website",
		]
		has_tests: true
	}
	"website_livechat": {
		dir: "addons/website_livechat"
		depends: [
			"im_livechat",
			"website",
		]
		has_tests: true
	}
	"website_mail": {
		dir: "addons/website_mail"
		depends: [
			"mail",
			"website",
		]
		has_tests: false
	}
	"website_mail_group": {
		dir: "addons/website_mail_group"
		depends: [
			"mail_group",
			"website",
		]
		has_tests: true
	}
	"website_mass_mailing": {
		dir: "addons/website_mass_mailing"
		depends: [
			"google_recaptcha",
			"mass_mailing",
			"website",
		]
		has_tests: true
	}
	"website_mass_mailing_sms": {
		dir: "addons/website_mass_mailing_sms"
		depends: [
			"mass_mailing_sms",
			"website_mass_mailing",
		]
		has_tests: true
	}
	"website_partner": {
		dir: "addons/website_partner"
		depends: [
			"website",
		]
		has_tests: false
	}
	"website_payment": {
		dir: "addons/website_payment"
		depends: [
			"account_payment",
			"portal",
			"website",
		]
		has_tests: true
	}
	"website_profile": {
		dir: "addons/website_profile"
		depends: [
			"gamification",
			"html_editor",
			"website_partner",
		]
		has_tests: true
	}
	"website_project": {
		dir: "addons/website_project"
		depends: [
			"project",
			"website",
		]
		has_tests: true
	}
	"website_sale": {
		dir: "addons/website_sale"
		depends: [
			"delivery",
			"digest",
			"html_builder",
			"portal_rating",
			"sale",
			"website",
			"website_mail",
			"website_payment",
		]
		has_tests: true
	}
	"website_sale_autocomplete": {
		dir: "addons/website_sale_autocomplete"
		depends: [
			"google_address_autocomplete",
			"website_sale",
		]
		has_tests: true
	}
	"website_sale_collect": {
		dir: "addons/website_sale_collect"
		depends: [
			"base_geolocalize",
			"payment_custom",
			"website_sale_stock",
		]
		has_tests: true
	}
	"website_sale_collect_wishlist": {
		dir: "addons/website_sale_collect_wishlist"
		depends: [
			"website_sale_collect",
			"website_sale_wishlist",
		]
		has_tests: false
	}
	"website_sale_comparison": {
		dir: "addons/website_sale_comparison"
		depends: [
			"website_sale",
		]
		has_tests: true
	}
	"website_sale_comparison_wishlist": {
		dir: "addons/website_sale_comparison_wishlist"
		depends: [
			"website_sale_comparison",
			"website_sale_wishlist",
		]
		has_tests: false
	}
	"website_sale_gelato": {
		dir: "addons/website_sale_gelato"
		depends: [
			"sale_gelato",
			"website_sale",
		]
		has_tests: true
	}
	"website_sale_loyalty": {
		dir: "addons/website_sale_loyalty"
		depends: [
			"sale_loyalty",
			"website_links",
			"website_sale",
		]
		has_tests: true
	}
	"website_sale_mass_mailing": {
		dir: "addons/website_sale_mass_mailing"
		depends: [
			"website_mass_mailing",
			"website_sale",
		]
		has_tests: true
	}
	"website_sale_mondialrelay": {
		dir: "addons/website_sale_mondialrelay"
		depends: [
			"delivery_mondialrelay",
			"website_sale",
		]
		has_tests: false
	}
	"website_sale_mrp": {
		dir: "addons/website_sale_mrp"
		depends: [
			"sale_mrp",
			"website_sale_stock",
		]
		has_tests: true
	}
	"website_sale_slides": {
		dir: "addons/website_sale_slides"
		depends: [
			"website_sale",
			"website_slides",
		]
		has_tests: true
	}
	"website_sale_stock": {
		dir: "addons/website_sale_stock"
		depends: [
			"sale_stock",
			"stock_delivery",
			"website_sale",
		]
		has_tests: true
	}
	"website_sale_stock_wishlist": {
		dir: "addons/website_sale_stock_wishlist"
		depends: [
			"website_sale_stock",
			"website_sale_wishlist",
		]
		has_tests: false
	}
	"website_sale_wishlist": {
		dir: "addons/website_sale_wishlist"
		depends: [
			"website_sale",
		]
		has_tests: true
	}
	"website_slides": {
		dir: "addons/website_slides"
		depends: [
			"portal_rating",
			"website",
			"website_mail",
			"website_profile",
		]
		has_tests: true
	}
	"website_slides_forum": {
		dir: "addons/website_slides_forum"
		depends: [
			"website_forum",
			"website_slides",
		]
		has_tests: false
	}
	"website_slides_survey": {
		dir: "addons/website_slides_survey"
		depends: [
			"survey",
			"website_slides",
		]
		has_tests: true
	}
	"website_sms": {
		dir: "addons/website_sms"
		depends: [
			"sms",
			"website",
		]
		has_tests: false
	}
	"website_timesheet": {
		dir: "addons/website_timesheet"
		depends: [
			"hr_timesheet",
			"website",
		]
		has_tests: false
	}
}
